### ISSUE TITLE
How to get all the history documents?

### ISSUE THREAD

**Issue by LaynezCoder** [WelingtonMonteiro/mongoose-history-trace#6]
I understand that this package has methods like: `Model.getChangeDiffs (old, current)` but I don't see that it has something like: `History.find({})` or `History.findById()`   where I can get all or some of the history documents. Beforehand thank you very much.

**Comment by WelingtonMonteiro** [comment]
Thank you for using this module. 
There really is no method to search for a document, as I understand that it is the dev's responsibility to implement it within their own project, as the purpose of this module is just to create the document diffs and save them in the database with the maximum amount of possible information.
If in the future a find method will be essential, I will implement it. But tell me, wouldn't it be simpler to create a search api in your own project with all the necessary queries? 
instead of using a restricted method of the module itself?
